In [1]:
import numpy as np

In [2]:
data1 = [6, 7.5, 8, 0, 1]
data1

[6, 7.5, 8, 0, 1]

In [3]:
# numpy를 이용하여 1차원 배열로 변형하기

arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [4]:
# 배열의 크기 확인
arr1.shape

(5,)

In [5]:
# 2차원 List
data2 = [
          [1, 2, 3, 4],
          [5, 6, 7, 8]
        ]
data2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [6]:
# numpy를 2차원 배열로 변형하기
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
arr2.shape

(2, 4)

In [9]:
# 0으로 구성된 1차원 배열 생성
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
# 5행 2열
np.zeros([5,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
# 3 page 5행 2열 : 3차원
np.zeros([3,5,2])

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [12]:
# 1로만 구성된 배열 생성
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
# 15로 가득찬 5개 array
np.full(5,15) 

array([15, 15, 15, 15, 15])

In [16]:
np.zeros((3,5)) # 3행 5열

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
# 숫자 8로 구성된 3행 5열
np.full((3,5),8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [23]:
# 범위가 있는 배열 생성
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
arr1.dtype

dtype('float64')

In [25]:
arr3 = np.array([1,2,3,4,5], dtype=np.int64)
arr3.dtype

dtype('int64')

In [26]:
# data type 변경
float_arr1 = arr3.astype(np.float64)
float_arr1.dtype

dtype('float64')

In [30]:
# 연산
arr1 = np.array([
    [1,2,3],
    [4,5,6]
], dtype=np.float64)
print(arr1,arr1.dtype)

[[1. 2. 3.]
 [4. 5. 6.]] float64


In [31]:
# 연산
arr2 = np.array([
    [7,8,9],
    [10,11,12]
], dtype=np.float64)
print(arr2,arr2.dtype)

[[ 7.  8.  9.]
 [10. 11. 12.]] float64


In [32]:
arr1 + arr2

array([[ 8., 10., 12.],
       [14., 16., 18.]])

In [33]:
arr1 - arr2

array([[-6., -6., -6.],
       [-6., -6., -6.]])

In [34]:
arr1 * arr2

array([[ 7., 16., 27.],
       [40., 55., 72.]])

In [35]:
arr1 / arr2

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [36]:
arr1 * 2

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [38]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [39]:
arr3 = 1 / arr1
arr3

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [40]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
arr[5]

5

In [42]:
arr[5:9]

array([5, 6, 7, 8])

In [43]:
arr[5:9] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

In [44]:
arr[:5]

array([0, 1, 2, 3, 4])

In [45]:
arr[8:]

array([12,  9])

### 2차원 배열

In [46]:
arr2d = np.array([
          [1, 2, 3, 4],
          [5, 6, 7, 8],
          [9, 10, 11, 12],
          [13, 14, 15, 16],
        ])
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [48]:
arr2d.dtype

dtype('int64')

In [58]:
# 2번 행의 자료 출력
arr2d[[2]]
arr2d[2,:]

array([ 9, 10, 11, 12])

In [67]:
# 1에서 2번 행의 자료 출력
arr2d[1:3,:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [68]:
# 3번 열의 자료 출력
arr2d[:,3]

array([ 4,  8, 12, 16])

In [72]:
# 0, 1 열의 자료 출력
arr2d[:,:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [71]:
# 1행 2열의 자료 출력
arr2d[1,2]

7

In [73]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [80]:
arr2d[:2,1:3] = 0

In [81]:
arr2d

array([[ 1,  0,  0,  4],
       [ 5,  0,  0,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

---
### 난수 발생
- rand: 0부터 1 사이의 균일분포
- randn: 가우시안 표준 정규분포 https://ko.wikipedia.org/wiki/정규_분포
- randint: 균일분포의 정수 난수

### Boolean Indexing

In [99]:
names = np.array(['Charles', 'Kenny', 'Hayoung', 'Charles', 'Hayoung', 'Kenny', 'Kenny'])
data = np.random.randn(7, 4)
data

array([[ 0.1070676 ,  0.53104844, -1.49469653,  0.2024219 ],
       [-0.14504171,  1.35970112, -0.16059686, -3.34625343],
       [ 1.05020751, -1.52138316, -0.91721053, -0.42713717],
       [ 0.91124549,  0.15722379,  1.11207359, -0.49698003],
       [ 0.76194351, -1.50323115,  0.99943552,  1.65307048],
       [-1.35086694,  0.94414433, -0.03881043, -0.22798471],
       [-0.96777468, -1.40061898, -0.69931342,  1.94244057]])

In [84]:
names

array(['Charles', 'Kenny', 'Hayoung', 'Charles', 'Hayoung', 'Kenny',
       'Kenny'], dtype='<U7')

In [85]:
names.shape

(7,)

In [87]:
data.shape

(7, 4)

In [88]:
# Mask를 이용한 추출
names == 'Charles'

array([ True, False, False,  True, False, False, False])

In [89]:
data[names == 'Charles']

array([[-1.57326037, -1.70100496,  0.38721281, -0.58862969],
       [ 0.43358368,  3.01305627, -0.6220667 ,  1.14938993]])

In [90]:
data[(names=="Charles") | (names == 'Kenny'),:]

array([[-1.57326037, -1.70100496,  0.38721281, -0.58862969],
       [-0.61239854,  1.22005554,  0.37365911, -0.40512959],
       [ 0.43358368,  3.01305627, -0.6220667 ,  1.14938993],
       [ 0.62865631, -0.99235386,  1.19872204,  0.78845042],
       [ 0.98209941, -0.24782099,  0.03618541, -0.8710136 ]])

In [91]:
data[:]

array([[-1.57326037e+00, -1.70100496e+00,  3.87212814e-01,
        -5.88629687e-01],
       [-6.12398539e-01,  1.22005554e+00,  3.73659112e-01,
        -4.05129591e-01],
       [-1.19397517e-01, -4.30285079e-01,  7.39086729e-01,
        -9.28418327e-01],
       [ 4.33583682e-01,  3.01305627e+00, -6.22066697e-01,
         1.14938993e+00],
       [ 2.74296729e+00,  8.93264322e-04,  1.80803573e-01,
         9.04797185e-01],
       [ 6.28656308e-01, -9.92353863e-01,  1.19872204e+00,
         7.88450423e-01],
       [ 9.82099409e-01, -2.47820989e-01,  3.61854147e-02,
        -8.71013599e-01]])

In [92]:
data[:, 3]

array([-0.58862969, -0.40512959, -0.92841833,  1.14938993,  0.90479719,
        0.78845042, -0.8710136 ])

In [94]:
# data의 4번째 열 값 중 0보다 작은 것의 mask 만들기
data[data[:, 3] < 0,:]

array([[-1.57326037, -1.70100496,  0.38721281, -0.58862969],
       [-0.61239854,  1.22005554,  0.37365911, -0.40512959],
       [-0.11939752, -0.43028508,  0.73908673, -0.92841833],
       [ 0.98209941, -0.24782099,  0.03618541, -0.8710136 ]])

In [100]:
# data의 4번째 열의 값이 0보다 작은 data들을 0으로 대체하기
data[data[:, 3]<0,:]=0
data[data[:, 3]<0,:]

array([], shape=(0, 4), dtype=float64)

In [101]:
data

array([[ 0.1070676 ,  0.53104844, -1.49469653,  0.2024219 ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.76194351, -1.50323115,  0.99943552,  1.65307048],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [-0.96777468, -1.40061898, -0.69931342,  1.94244057]])

In [103]:
# 정렬
arr = np.random.rand(8)
arr

array([0.18431962, 0.53023876, 0.33237902, 0.26621192, 0.23628442,
       0.13054167, 0.38828575, 0.8414424 ])

In [104]:
# 오름차순 정렬
np.sort(arr)

array([0.13054167, 0.18431962, 0.23628442, 0.26621192, 0.33237902,
       0.38828575, 0.53023876, 0.8414424 ])

In [105]:
# 내림차순 정렬
np.sort(arr)[::-1]

array([0.8414424 , 0.53023876, 0.38828575, 0.33237902, 0.26621192,
       0.23628442, 0.18431962, 0.13054167])

In [106]:
arr = np.random.rand(5,3)
arr

array([[0.5763995 , 0.77731632, 0.32636886],
       [0.47758196, 0.59413747, 0.9852261 ],
       [0.04274744, 0.14857671, 0.54232531],
       [0.38025632, 0.63513886, 0.22598515],
       [0.60445088, 0.53880034, 0.37884788]])

In [107]:
np.sort(arr, axis = 0) # axis = 0, 열방향 오름차순

array([[0.04274744, 0.14857671, 0.22598515],
       [0.38025632, 0.53880034, 0.32636886],
       [0.47758196, 0.59413747, 0.37884788],
       [0.5763995 , 0.63513886, 0.54232531],
       [0.60445088, 0.77731632, 0.9852261 ]])

In [108]:
np.sort(arr, axis = 1) # axis = 1 행방향 오름차순

array([[0.32636886, 0.5763995 , 0.77731632],
       [0.47758196, 0.59413747, 0.9852261 ],
       [0.04274744, 0.14857671, 0.54232531],
       [0.22598515, 0.38025632, 0.63513886],
       [0.37884788, 0.53880034, 0.60445088]])

In [109]:
np.sort(arr, axis = 0)[::-1] # axis = 0, 열방향 내림차순

array([[0.60445088, 0.77731632, 0.9852261 ],
       [0.5763995 , 0.63513886, 0.54232531],
       [0.47758196, 0.59413747, 0.37884788],
       [0.38025632, 0.53880034, 0.32636886],
       [0.04274744, 0.14857671, 0.22598515]])

In [115]:
np.sort(arr, axis = 1)[:,::-1] # axis = 1, 행방향 내림차순

array([[0.77731632, 0.5763995 , 0.32636886],
       [0.9852261 , 0.59413747, 0.47758196],
       [0.54232531, 0.14857671, 0.04274744],
       [0.63513886, 0.38025632, 0.22598515],
       [0.60445088, 0.53880034, 0.37884788]])

In [116]:
# 중복 제거
np.unique(names)

array(['Charles', 'Hayoung', 'Kenny'], dtype='<U7')

---
### reshape

In [118]:
arr = np.arange(1,9)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [119]:
arr.shape

(8,)

In [120]:
# 2차원 배열로 변경
arr1 = np.reshape(arr, (2,4))
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [122]:
# 3차원 배열로 변경
arr2 = np.reshape(arr,(2,2,2))
arr2

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [136]:
# 2차원 배열을 1차원으로 변경
arr3 = arr1.reshape(-1) # 데이터 수를 모를 때 -1로 차원을 줄여준다.
arr3

array([1, 2, 3, 4, 5, 6, 7, 8])

In [134]:
arr4 = arr2.reshape(-1, 1) # 딥러닝에서는 차원 표시(열 수)를 1로 해줘야 한다.
arr4

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [130]:
arr5 = arr2.reshape(-1)
arr5

array([1, 2, 3, 4, 5, 6, 7, 8])

In [137]:
arr3 == arr4

array([[ True, False, False, False, False, False, False, False],
       [False,  True, False, False, False, False, False, False],
       [False, False,  True, False, False, False, False, False],
       [False, False, False,  True, False, False, False, False],
       [False, False, False, False,  True, False, False, False],
       [False, False, False, False, False,  True, False, False],
       [False, False, False, False, False, False,  True, False],
       [False, False, False, False, False, False, False,  True]])