![](../data/%EC%9D%B8%EA%B3%B5%EC%8B%A0%EA%B2%BD%EB%A7%9D2.png)

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('../data/gpascore.csv')
data.head()

admit    gre   gpa  rank
0      0  380.0  3.21     3
1      1  660.0  3.67     3
2      1  800.0  4.00     1
3      1  640.0  3.19     4
4      0  520.0  2.33     4

> 미국 대학   
admit : 합격/불합격,   
gre : 영어 성적,   
gpa : 학점,    
rank : 지원한 대학원 등급   

### Preprocessing(전처리)

In [3]:
# 결측치 처리
data.isnull().sum()

admit    0
gre      1
gpa      0
rank     0
dtype: int64

In [4]:
# 결측치 데이터 삭제
data.dropna(inplace=True)

# 결측치 데이터 치환
# data.fillna(100, inplace=True)

In [5]:
data.isnull().sum()

admit    0
gre      0
gpa      0
rank     0
dtype: int64

In [6]:
# rank의 종류 파악
data['rank'].value_counts()

2    158
3    129
4     71
1     67
Name: rank, dtype: int64

In [7]:
sorted(data['rank'].unique())

[1, 2, 3, 4]

In [8]:
# 영어 점수의 최소, 최대값
print('최대 :', data.gre.max())
print('최소 :', data.gre.min())

최대 : 800.0
최소 : 220.0


In [9]:
# Train Data
x = data[['gre', 'gpa', 'rank']]
x.head()

gre   gpa  rank
0  380.0  3.21     3
1  660.0  3.67     3
2  800.0  4.00     1
3  640.0  3.19     4
4  520.0  2.33     4

In [10]:
# Target Data
y = data['admit']
y.head()

0    0
1    1
2    1
3    1
4    0
Name: admit, dtype: int64

In [11]:
x.count()

gre     425
gpa     425
rank    425
dtype: int64

> 입력층 3개, gre/gpa/rank   
> 출력층 1개, admit : 0과 1의 이진분류, sigmoid 함수 활용   
> 입력층을 제외하고 1개 층을 가지고 있다.

---
Deep Learning Model 만들기 2

In [12]:
from tensorflow import keras

In [13]:
input_layer = keras.layers.InputLayer(input_shape=(3,))
hidden_layer = keras.layers.Dense(256, activation='tanh')
output_layer = keras.layers.Dense(1, activation='sigmoid')

In [14]:
# sequential, add할 때마다 층이 하나씩 쌓인다.
model = keras.Sequential(
    [
        input_layer,
        hidden_layer,
        output_layer
    ]
)

2022-07-20 10:57:49.717927: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [15]:
# 손실함수
model.compile(optimizer='adam', loss='binary_crossentropy', metrics='accuracy') 
# sparse는 입력값이 실수라 쓸 수 없다.
# binary_crossentropy : 분류 및 확률 예측
# metrics : 모델의 평가 기준

In [16]:
# 학습시키기
# 현재 data가 pandas에 들어있음
import numpy as np

In [21]:
model.fit(np.array(x), np.array(y), epochs=110) # verbose : 진행상황 출력 여부

Epoch 1/110
14/14 [==============================] - 0s 3ms/step - loss: 0.6553 - accuracy: 0.6118
Epoch 2/110
14/14 [==============================] - 0s 2ms/step - loss: 0.6421 - accuracy: 0.6518
Epoch 3/110
14/14 [==============================] - 0s 1ms/step - loss: 0.6655 - accuracy: 0.6071
Epoch 4/110
14/14 [==============================] - 0s 1ms/step - loss: 0.6398 - accuracy: 0.5976
Epoch 5/110
14/14 [==============================] - 0s 2ms/step - loss: 0.6306 - accuracy: 0.6494
Epoch 6/110
14/14 [==============================] - 0s 3ms/step - loss: 0.6543 - accuracy: 0.6047
Epoch 7/110
14/14 [==============================] - 0s 2ms/step - loss: 0.6576 - accuracy: 0.6329
Epoch 8/110
14/14 [==============================] - 0s 2ms/step - loss: 0.6404 - accuracy: 0.6353
Epoch 9/110
14/14 [==============================] - 0s 2ms/step - loss: 0.6437 - accuracy: 0.6094
Epoch 10/110
14/14 [==============================] - 0s 3ms/step - loss: 0.6923 - accuracy: 0.5529
Epoch 11/

In [22]:
# hidden layer의 가중치 값 출력
hidden_layer.get_weights()[0]

array([[-3.29756700e-02,  1.40673697e-01, -1.24055028e-01,
        -3.37925404e-02, -1.40761882e-01, -5.06848991e-02,
        -2.15082485e-02,  7.94979781e-02,  2.11941898e-02,
        -7.06144720e-02,  8.69162381e-02, -3.39378640e-02,
         1.34140670e-01,  5.21346182e-02, -1.23129323e-01,
        -1.39742009e-02, -1.20502412e-01,  1.29512936e-01,
        -8.53521451e-02, -1.02104276e-01, -5.17840311e-03,
        -1.39209434e-01,  1.30625516e-01,  1.09559774e-01,
         6.13160133e-02, -5.70994318e-02, -1.49214685e-01,
        -7.97191933e-02,  4.70412672e-02,  1.48652829e-02,
         9.45547223e-02,  1.36970997e-01,  1.20001048e-01,
         6.31569177e-02, -6.14385232e-02,  3.27882469e-02,
        -1.48674309e-01, -9.52510983e-02,  3.83203775e-02,
         1.02968842e-01,  1.48355663e-01,  1.42428756e-01,
        -4.19301093e-02,  5.39388657e-02, -2.38738162e-03,
        -3.78116108e-02, -1.08201280e-01,  1.04814708e-01,
         9.54710841e-02,  1.03299707e-01, -1.26853943e-0

In [25]:
# hidden layer의 절편 값 출력
hidden_layer.get_weights()[1]

array([-1.6245999e-03,  0.0000000e+00,  0.0000000e+00, -5.4386433e-04,
        0.0000000e+00,  0.0000000e+00,  9.2735395e-02,  0.0000000e+00,
        6.0752042e-02,  0.0000000e+00,  0.0000000e+00, -9.2982482e-05,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  1.8019426e-01,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        4.3284386e-01,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  6.2026009e-02,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00, -1.0236741e-05,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        5.2923137e-01, -3.6341262e-05,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
      

In [23]:
# hidden layer의 출력 확인하기
intermediate_layer_model = keras.Model(inputs=model.input, outputs=model.layers[0].output)
intermediate_output = intermediate_layer_model(np.array(x))

In [24]:
intermediate_output

<tf.Tensor: shape=(425, 256), dtype=float32, numpy=
array([[-1.,  1., -1., ...,  1.,  1., -1.],
       [-1.,  1., -1., ...,  1.,  1., -1.],
       [-1.,  1., -1., ...,  1.,  1., -1.],
       ...,
       [-1.,  1., -1., ...,  1.,  1., -1.],
       [-1.,  1., -1., ...,  1.,  1., -1.],
       [-1.,  1., -1., ...,  1.,  1., -1.]], dtype=float32)>